In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
# class representing your neural network
# 4 (input) --> 3 (hidden layer) --> 2 (hidden layer) --> 1 (output layer)

class SinglePerceptron(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden_layer_1 = torch.nn.Linear(4, 3) # input to first hidden layer
        self.hidden_layer_2 = torch.nn.Linear(3, 2)
        self.output_layer = torch.nn.Linear(2, 1)

        # activation
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        # hidden layer 1 activation
        x = self.sigmoid(self.hidden_layer_1(x))

        # hidden layer 2 activation
        x = self.sigmoid(self.hidden_layer_2(x))
        
        # output layer activation
        y = self.sigmoid(self.output_layer(x))
        return y

In [3]:
x = torch.Tensor([[5,3,1,2],[2,5,6,8]])
model = SinglePerceptron()
predictions = model.forward(x)
print(predictions.shape)
print(model)

torch.Size([2, 1])
SinglePerceptron(
  (hidden_layer_1): Linear(in_features=4, out_features=3, bias=True)
  (hidden_layer_2): Linear(in_features=3, out_features=2, bias=True)
  (output_layer): Linear(in_features=2, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [4]:
# Loss function
loss_fn = nn.MSELoss()

answer_key = torch.Tensor([[1], [0]])

for i in range(len(predictions)):
    p = predictions[i]
    a = answer_key[i]

    loss = loss_fn(p, a)

    print(loss.item())

0.32789644598960876
0.1831338256597519


In [5]:
# Examine the parameters
num_parameters = 0
for name, param in model.named_parameters():
    print(name)
    print(param.data)
    
    num_parameters += param.numel()

hidden_layer_1.weight
tensor([[-0.2305, -0.2224,  0.3931,  0.3562],
        [ 0.0011,  0.1016, -0.3186, -0.4157],
        [ 0.4749, -0.4675,  0.2004, -0.4947]])
hidden_layer_1.bias
tensor([0.4116, 0.1549, 0.1240])
hidden_layer_2.weight
tensor([[-0.5222, -0.2861, -0.4843],
        [-0.1735, -0.3987,  0.0451]])
hidden_layer_2.bias
tensor([0.4529, 0.2222])
output_layer.weight
tensor([[ 0.1608, -0.3112]])
output_layer.bias
tensor([-0.2084])


In [6]:
# Number of parameters of the network, weights plus biases
print("Num Parameters: {}".format(num_parameters))

Num Parameters: 26


In [7]:
# Check the state of the model as a dictionary
print(model.state_dict())

OrderedDict([('hidden_layer_1.weight', tensor([[-0.2305, -0.2224,  0.3931,  0.3562],
        [ 0.0011,  0.1016, -0.3186, -0.4157],
        [ 0.4749, -0.4675,  0.2004, -0.4947]])), ('hidden_layer_1.bias', tensor([0.4116, 0.1549, 0.1240])), ('hidden_layer_2.weight', tensor([[-0.5222, -0.2861, -0.4843],
        [-0.1735, -0.3987,  0.0451]])), ('hidden_layer_2.bias', tensor([0.4529, 0.2222])), ('output_layer.weight', tensor([[ 0.1608, -0.3112]])), ('output_layer.bias', tensor([-0.2084]))])


In [8]:
# Declare a dictionary that we want to serialize as .pth file
state = { 'state_dict': model.state_dict() }

torch.save(state, "model.pth")

In [9]:
# Load a model
model = SinglePerceptron()

state = torch.load("model.pth")

model.load_state_dict(state['state_dict'])

predictions = model.forward(x)

predictions

tensor([[0.4274],
        [0.4279]], grad_fn=<SigmoidBackward0>)

In [10]:

# Convert a tensor back to a numpy array
preds = predictions.detach().cpu().numpy()

print(preds)

[[0.4273776 ]
 [0.42794138]]
